---
title: "a3_task3_julia_wilson.RMD"
author: "Julia Wilson"
date: "10/23/2021"
output: html_document
---
### Set Up 
```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(janitor)
library(lubridate)
library(kableExtra)
```

## Section 1
### Read in the Data
```{r, message = FALSE}
# Read in urchins.csv data and name "urchins_data"
urchins_data <- read_csv(here("data", "urchins.csv"))
```

### Wrangle Data
```{r}
# Clean data names with clean_names()
urchins_clean <- urchins_data %>% 
  clean_names()
```


### Visualize Data
```{r}
ggplot(data = urchins_clean, aes(x = size)) +
  geom_histogram(color = "red", fill = "white", bin = 10) +
  facet_grid(common_name ~ .) + 
  labs(x = "Urchin Diameter (cm)", 
       y = "Count",
       title = "Purple and Red Urchin Sizes",
       caption = "Figure 1: ") 
```


### Descriptive Statistics Table
```{r}
# Create a finalized summary table using kableEXTRA
urchins_summary <- urchins_clean %>% 
  group_by(common_name) %>% 
  summarize(mean = mean(size),
            median = median(size),
            sd = sd(size),
            sample_size = n()) %>% 
  kable(caption = "Table 1: Summary Statistics of Urchin Sizes",
        col.names = c("Urchin Name",
                      "Mean (cm)",
                      "Median(cm)",
                      "Standarad Deviation",
                      "Sample Size"),
        digits = 1) %>% 
  kable_minimal()

urchins_summary
```



## Section 2
```{r}
purple_urchins <- urchins_clean %>% 
  filter(common_name == "Purple Urchin") %>% 
  mutate(date_new = mdy(date)) %>% 
  mutate(year_new = year(date_new)) %>% 
  mutate(site_full = case_when(
    site == "NAPL" ~ "Naples Reef",
    site == "MOHK" ~ "Mohawk Reef",
    site == "IVEE" ~ "Isla Vista Reef",
    site == "AQUE" ~ "Arroyo Quemado Reef",
    site == "CARP" ~ "Carpinteria Reef"
  ))
```

```{r}
purple_urchin_summary <- purple_urchins %>% 
  group_by(site_full, year_new) %>% 
  summarize(sample_size = n())

purple_urchin_summary
```

```{r}
ggplot(data = purple_urchin_summary, 
       aes(x = year_new, y = sample_size, color = site_full)) +
  geom_bar(stat = "identity") +
  aes(fill = site_full) +
  labs(x = "Year",
       y = "Count of Purple Urchins",
       title = "Total Purple Urchin Count per Site (2008 -2020)")
```
Figure Caption: 
Text:
